### ISSUE TITLE
Initial restyling of program and movie detail

### ISSUE THREAD

**Issue by schachdavid** [afuetterer/cinemabear#138]
restyle program and movie detail as discussed, wireframe:
![image](https://user-images.githubusercontent.com/45998057/61306206-79da9780-a7ec-11e9-93c0-82f6b694cc8e.png)

**Comment by afuetterer** [comment]
I added filtering capabilities to the ScreeningManager. You can now filter Screenings by genre, cinema and the discussed date filters.
