### ISSUE TITLE
Choose logo

### ISSUE THREAD

**Issue by afuetterer** [afuetterer/cinemabear#17]
For now: https://emojipedia.org/bear-face/

**Comment by reallinfo** [comment]
Hi @afuetterer 

If you want to use a more functional and original logo I have designed a logo for this repo. Please let me know what you think. Have a nice day :)

![cinemabear](https://user-images.githubusercontent.com/36298335/57134256-402def00-6dae-11e9-8d09-974fea3c511e.jpg)

**Comment by reallinfo** [comment]
Also, Readme view;

![cine2](https://user-images.githubusercontent.com/36298335/57134309-71a6ba80-6dae-11e9-8ce1-0da5ad95b1af.png)

**Comment by afuetterer** [comment]
Thanks @reallinfo for the offer, let me think about it.
At first sight I think the logo looks a bit scary now with the merger of bear face and film roll (?).

**Comment by reallinfo** [comment]
Oh okay, I made the logo a little sweeter.  What do you think now?

![cine](https://user-images.githubusercontent.com/36298335/57179008-8bfd9880-6e81-11e9-88da-b623262b54e0.jpg)
